### ISSUE TITLE
Не могу создать юзера со строкой вместо телефона

### ISSUE THREAD

**Issue by jehkinen** [flyingleafe/pyatachok#10]
*Это относится к созданию админов и модераторов

$user->fill(array(
            'phone'     =>  Input::get('phone'), //нет в модели если тут строка наприме такая '905174546f'
            'password'  => Input::get('password'),
            'role'  => Input::get('role'),
        ));
$user->save(); естественно вызывает ошибку

SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "phone" violates not-null constraint

SQL: INSERT INTO "users" ("password", "role", "updated_at", "created_at") VALUES (?, ?, ?, ?) RETURNING id

//как видно, в phone вообще нет при вставке
Bindings: array (
  0 => '$2a$08$MUNxcHRpUWVVc0RyaGZZcOXZpiEiJ7/6BTok8Q9Mn7JXGKoXjT.Xu',
  1 => '1',
  2 => '2013-03-11 14:59:05',
  3 => '2013-03-11 14:59:05',
)

 Input::get('phone') - если тут строка, содержащая символы (строка ввиде номера телефона из цифр вставляется), то из модели упорно вырезается телефон, бред полный. (если переименовать колонку phone в бд или вставить через pgadmin, то вставляет)

**Comment by flyingleafe** [comment]
Странно, я вроде перед приведением телефона к общему виду в модели сделал условие, чтобы не-телефоны не обрабатывались. Сегодня посмотрю, исправлю и напишу тесты.
