### ISSUE TITLE
Вёрстка главной

### ISSUE THREAD

**Issue by jehkinen** [flyingleafe/pyatachok#11]
1) Весь макет свёрстан под 1600px, я не вижу что я должен ужать, если разрешение меньше. *главное меню не влезет  на мониторе меньшего разрешения - пока это основная проблема, почему я не начал верстать.

2)Градиент фона - не могу выделить кусок, что бы его репитнуть по вертикали и горизонтали (вообщем лучше выслать файлик с градиентом, либо сделать понятным градиент: как он репитится)

3) Стили меню при наведении, что меняется при наведении на главное меню? (Моя анкета, отзывы)

**Comment by flyingleafe** [comment]
1) так, щас напишу дезигнеру, чтобы ужал все хотя бы до 960. макеты делаю, как ты понял уже, не я, и, честно тебе сказать, тот человек не особо опытен в подготовке макетов.
2) если ты про серый фон, то гляди мой последний коммит: я там разрезал его, получилось вполне адекватно.
3) осветление фона, опять же, смотри мой коммит.
