### ISSUE TITLE
Поиск рабочих без какой-либо категории

### ISSUE THREAD

**Issue by jehkinen** [flyingleafe/pyatachok#3]
Непонятно как нужно ли выводить рабочих, у которых нет никаких категорий.
И как это будет выглядеть? Допустим у некоторых рабочих есть категории а у некоторых нет ( т.е. у некоторые рабочие выводятся с тегами типов работ и их стоимостью, а некоторые просто с телефонон и  именем?)

**Comment by flyingleafe** [comment]
Мы это уже вроде обсуждали. У рабочего не может быть ни одной категории - пока он не выберет хоть одну, у него стоит статус 1 (незаполненный профиль), и он не появляется в поиске. Смысла нет делать возможность не выбирать категории.
