### ISSUE TITLE
Блокировка выбора зарплаты без выбранной категории работ

### ISSUE THREAD

**Issue by jehkinen** [flyingleafe/pyatachok#4]
Скорее всего в поиске нужно блокировать выбор диапазона зарплат, если не выбран тип работ, т.к. поиск производится в таблице jobtype_user, можно конечно выбирать все записи с таким диапазоном зарплат (cost) но целесообразно ли это?

**Comment by flyingleafe** [comment]
Да, пока заблокируем. Нам надо побыстрее реализовать, если вдруг понадобится потом (что вряд ли) - что-нибудь придумаем.
