### ISSUE TITLE
Шаблонизатор blade, присвоение без echo

### ISSUE THREAD

**Issue by jehkinen** [flyingleafe/pyatachok#5]
Ты говорил не использовать php short_tags, но как с помощью шаблонизатора blade сделать присвоение без вывода,  {{ some code ... }} такая конструкция потом интерпретируется laravel  как <?php echo ... ?>
Но если требуется в представлении сделать присвоение переменной
{{ $array = array(1,2,3) }} - получим ошибку array to string conversion

**Comment by flyingleafe** [comment]
Я был не совсем прав. Просто юзай <?php ... ?>. Короткие тэги все-таки не надо, моветон как бы.

**Comment by jehkinen** [comment]
ты может в скайп бы вышел?
