### ISSUE TITLE
Не работает вход для сгенеренных пользвателей

### ISSUE THREAD

**Issue by jehkinen** [flyingleafe/pyatachok#9]
Не могу понять в чём дело, но ты там заменил авторизацию на 1 строку и авторизация перестала работать для генерируемых юзеров

**Comment by flyingleafe** [comment]
вопрос: а ты как вообще заходил за этих пользователей когда-либо, там же все пароли случайны, ты их не знашь? О_о

**Comment by jehkinen** [comment]
пароль для всех 1234, посмотри в код генератора

**Comment by flyingleafe** [comment]
Кажется понял. Дело не в нормальной аутентификации, а в том, что я сделал сеттер пароля для модели юзера - он хешируется автоматически, и вручную вызывать Hash::make не надо. То есть делается хэш от хэша. Убери хэшмейк из генератора.
